#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/ddev/ddev-drupal-contrib
## Description: Run eslint inside the web container
## Usage: eslint [target] [flags] [args]
## Example: "ddev eslint" (runs against all projects in $DRUPAL_PROJECTS_PATH)
## Example: "ddev eslint ." (runs against the current working directory)
## Example: "ddev eslint web/modules/custom/mymodule" (runs against a specific directory)
## ExecRaw: true

set -eu -o pipefail

if "$DDEV_DOCROOT/core/node_modules/.bin/eslint" --version >/dev/null ; then
  # Configure prettier in working directory (searched by prettier traversing up)
  test -e .prettierrc.json || ln -s $DDEV_DOCROOT/core/.prettierrc.json .
  test -e .prettierignore || echo '*.yml' > .prettierignore
  # Use first arg as target directory if it exists as a path
  if [ $# -gt 0 ] && [[ "$1" != -* ]] && [ -e "$1" ]; then
    TARGET_DIR="$1"
    shift
  else
    TARGET_DIR="$DDEV_DOCROOT/$DRUPAL_PROJECTS_PATH"
  fi
  cd "$TARGET_DIR" || exit
  "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/core/node_modules/.bin/eslint" --config="$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/core/.eslintrc.passing.json" --no-error-on-unmatched-pattern --ignore-pattern="*.es6.js" --resolve-plugins-relative-to=$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/core --ext=.js,.yml . "$@"
else
  echo "eslint is not available. You may need to 'ddev exec \"cd $DDEV_DOCROOT/core && yarn install\"'"
  exit 1
fi
