#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/ddev/ddev-drupal-contrib
## Description: Run phpcs inside the web container
## Usage: phpcs [target] [flags] [args]
## Example: "ddev phpcs" (runs against all projects in $DRUPAL_PROJECTS_PATH)
## Example: "ddev phpcs ." (runs against the current working directory)
## Example: "ddev phpcs web/modules/custom/mymodule" (runs against a specific directory)
## ExecRaw: true

set -eu -o pipefail

if ! command -v phpcs >/dev/null; then
  echo "phpcs is not available. You may need to 'ddev composer install'"
  exit 1
fi
test -e phpcs.xml.dist || curl -OL https://git.drupalcode.org/project/gitlab_templates/-/raw/default-ref/assets/phpcs.xml.dist
if [ $# -gt 0 ] && [[ "$1" != -* ]] && [ -e "$1" ]; then
  TARGET_PATH="$1"
  shift
else
  TARGET_PATH="$DDEV_DOCROOT/$DRUPAL_PROJECTS_PATH"
fi
phpcs -s --report-full --report-summary --report-source "$TARGET_PATH" --ignore=*/.ddev/* "$@"
